# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseer < Formula
  desc "Overseer - A terminal UI application"
  homepage "https://github.com/dnlopes/overseer"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dnlopes/overseer/releases/download/v1.5.0/overseer_1.5.0_darwin_amd64.tar.gz"
      sha256 "e314e3793cadd9dd712e82a508d379169e21ec4afda3354615d5fe9b86f6144c"

      define_method(:install) do
        bin.install "overseer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dnlopes/overseer/releases/download/v1.5.0/overseer_1.5.0_darwin_arm64.tar.gz"
      sha256 "71da7159c6d2bccd10c18bcd8ff9b218560a91dde3c8c0153be890ab3dacebc7"

      define_method(:install) do
        bin.install "overseer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnlopes/overseer/releases/download/v1.5.0/overseer_1.5.0_linux_amd64.tar.gz"
      sha256 "f8c95277cefb56f9c75569e21f338a69783ca33f6797b8faa649783af281f273"
      define_method(:install) do
        bin.install "overseer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnlopes/overseer/releases/download/v1.5.0/overseer_1.5.0_linux_arm64.tar.gz"
      sha256 "3032afa433a7384b94a7b325ebea290043269534d732583b1db4075bc513951b"
      define_method(:install) do
        bin.install "overseer"
      end
    end
  end

  test do
    system "#{bin}/overseer --version"
  end
end
