# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overseer < Formula
  desc "Overseer - A terminal UI application"
  homepage "https://github.com/dnlopes/overseer"
  version "1.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dnlopes/overseer/releases/download/v1.1.4/overseer_1.1.4_darwin_amd64.tar.gz"
      sha256 "0417d0232dbabff41b7315a87070a063c6e2930a306c8cb52a2b7173d373bc9f"

      define_method(:install) do
        bin.install "overseer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dnlopes/overseer/releases/download/v1.1.4/overseer_1.1.4_darwin_arm64.tar.gz"
      sha256 "320853347feece73e1397ff7b18c9b3851f11a341dcc1132563daabb5bd6f343"

      define_method(:install) do
        bin.install "overseer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnlopes/overseer/releases/download/v1.1.4/overseer_1.1.4_linux_amd64.tar.gz"
      sha256 "85481b45452181a97571751e7b5bc0a7e42637212b90d54a1befb921ed682dec"
      define_method(:install) do
        bin.install "overseer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnlopes/overseer/releases/download/v1.1.4/overseer_1.1.4_linux_arm64.tar.gz"
      sha256 "a82c8aabdb790e65e045351e6d0c258f9a968efa792a1263796ff26aa6c262e3"
      define_method(:install) do
        bin.install "overseer"
      end
    end
  end

  test do
    system "#{bin}/overseer --version"
  end
end
